[package]
name = "aprstream"
version = "0.1.0"
edition = "2021"

[dependencies]
aprs-parser = "0.4.2"
geoutils = "0.5.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
ureq = { version = "2.9.7", features = ["json"] }
